import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import StoreProvider from "./StoreProvider";
import { Toaster } from "sonner";
import Products from "@/components/Products";
import ProductsWrapper from "@/components/ProductsWrapper";
import Wrapper from "@/components/Wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Redux | Axios",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Toaster />
          <Navbar />
          <Wrapper />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
